// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for portifolio documents */
interface PortifolioDocumentData {
    /**
     * title field in *portifolio*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * image field in *portifolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * language field in *portifolio*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.language
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    language: prismicT.RichTextField;
    /**
     * description field in *portifolio*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * technology field in *portifolio*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.technology
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    technology: prismicT.RichTextField;
    /**
     * github field in *portifolio*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.github
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    github: prismicT.LinkField;
    /**
     * deploy field in *portifolio*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: portifolio.deploy
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    deploy: prismicT.LinkField;
}
/**
 * portifolio document from Prismic
 *
 * - **API ID**: `portifolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortifolioDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PortifolioDocumentData>, "portifolio", Lang>;
export type AllDocumentTypes = PortifolioDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PortifolioDocumentData, PortifolioDocument, AllDocumentTypes };
    }
}
